export const FETCH_TOKOMON_LIST = "FETCH_TOKOMON_LIST";
export const FETCH_TOKOMON_DATA = "FETCH_TOKOMON_DATA";
export const START_FETCHING = "START_FETCHING";
export const END_FETCHING = "END_FETCHING";
export const ADVANCE_PAGE = "ADVANCE_PAGE";
export const CATCH_TOKOMON = "CATCH_TOKOMON";
export const RELEASE_TOKOMON = "RELEASE_TOKOMON";
